### ISSUE TITLE
Deploying contract on Ropsten TestNet

### ISSUE THREAD

**Issue by tpmccallum** [second-state/buidl#1]
It appears that we will need to provide a gas value in the `sendTransaction()` method when pointing BUIDL to Ethereum networks (Ropsten TestNet included).

The simple storage contract compiles successfully in BUIDL but when it is deployed to Ropsten the following error is displayed in the BUIDL log output 

`Error: exceeds block gas limit`

If we alter the `sendTransaction` code which executes at [1] then this contract may successfully deploy on the Ropsten TestNet.

There is a section of BUIDL code which has the potential to add the appropriate Ethereum gas parameters to the raw BUIDL transaction [2]. 

To ensure that this is not hard coded, perhaps we could have a button/switch in the BUIDL web console which allows us to toggle ETH gas on and off.

[1] https://github.com/second-state/buidl/blob/839f187ecfdd98d25fd1b2e47fd3457350e197a9/src/services/web3.ts#L49  
[2] https://github.com/second-state/buidl/blob/839f187ecfdd98d25fd1b2e47fd3457350e197a9/src/services/web3.ts#L27

**Comment by juntao** [comment]
I think this can be done in web3? That is — to add gas in the JavaScript and do not modify BUIDL.

-----------------------------
Michael Yuan, PhD
http://www.michaelyuan.com

________________________________

**Comment by wangshishuo** [comment]
Just added the customization support for gas in the web3 provider section.
