### ISSUE TITLE
Import Accounts Broken

### ISSUE THREAD

**Issue by joesixpack** [second-state/buidl#19]
![image](https://user-images.githubusercontent.com/23145642/96356529-aabb1380-10a4-11eb-9ebd-a0c0f7960343.png)

Metamask does not provide private keys for individual accounts (anymore?), only a mnemonic phrase that covers all possible generated accounts.

Regardless, it did not recognize a secret key generated in MEW when I tried importing.  Directions should be included to add 0x to it.

**Comment by tpmccallum** [comment]
Just click on the 3 vertical dots and select "Account details"

![Screen Shot 2020-10-18 at 11 27 47 am](https://user-images.githubusercontent.com/9831342/96356647-092fd280-1135-11eb-988e-34d5eef0567e.png)

Then click the "Export private key" button.

![Screen Shot 2020-10-18 at 11 26 50 am](https://user-images.githubusercontent.com/9831342/96356641-e4d3f600-1134-11eb-8eb0-9cc34249abc6.png)

The private key that MetaMask gives you does not start with the text `0x`. You need to add a `0x` to the start of the private key; then it will be imported into BUIDL.

**Comment by tpmccallum** [comment]
Remember to add the `0x` when you paste it into BUIDL :)

**Comment by joesixpack** [comment]
Ah, thanks, thats totally nonintuitive.
